### PR TITLE
Add functionality to test arbitrary distributions. 

### PR DESCRIPTION
**Pull request by yashpote**
Barbarik has been extended to allow for the testing of arbitrary weighted distributions. In this PR, I took the code of the weighted version of Barbarik and merged it with the uniform version. We do not replace uniform Barbarik, as for uniform distributions, it performs better.

### CODE REVIEW

**Comment by msoos** [comment]
Hi Yash,

Thanks, it's great to see Barbarik being worked on! I am glad you have looked at this code and worked on improving it, good stuff :) However, I have a few things I'd like to have improved about this PR. I think it could be made cleaner and easier to check for someone like me.

## Major questions/issues
* First of all, why Barbarik and not Scalbarbarik? A lot of old code was improved in ScalBarbarik. Why did you use Barbarik as the base of this change? Is there some specific reason?
* Please try to explain this PR, currently it only has a title :( Please write a few paragraphs  so I can better understand & review and hopefully able to give better feedback to you!

## Smaller questions/issues
* Have you stripped all binaries? All binaries should have `strip (binaryname)` ran before adding them. Otherwise they are huge. Unstripped binaries will make it very hard for users to use the tool
* Why the empty __init__.py file? Is this part of WAPS
* Which version of d4 did you upload? Perhaps the version could be added to the name?
* Did you copy-paste WAPS? If so, why? Can't it be a submodule? What's wrong having it as a submodule?
* weighted-to-unweighted should be a submodule, not copy-pasted. The submodule can be "pinned" to a commit, so it won't break underneath you when people change what you depend on. You can say which exact commit should be used and then it'll be the one checked out when users do `git submodule init` && `git submodule update`.


[Ignore the following if your binaries are stripped!] After you have fixed the unstripped binarye, squashing your commits is a _must_. Please read about squashing your git commits. You can simply squash them on your branch and then force-push to the branch that is the PR branch (`add_weights`). This will make all your work look like a single commit. This is needed because you likely committed unstripped binaries which are large and will bloat the git history. If you push a new, stripped binary it will actually make the git history even larger :laughing: . Hence, squashing of your commits is needed so we only upload the stripped binary.

I hope the above helps and I'm looking forward to a slightly cleaner PR and some description of what this PR is doing :)

Thanks again for the work,

Mate

**Comment by yashpote** [comment]
Hi Mate,

Thanks for taking the time to review my edits!

> First of all, why Barbarik and not Scalbarbarik? A lot of old code was improved in ScalBarbarik. Why did you use 
Barbarik as the base of this change? Is there some specific reason?

We have decided to not merge the ScalBarbarik functionality of "computational hardness" into Barbarik. However, I will go over the other changes and I will incorporate them into this PR. 

> Which version of d4 did you upload? Perhaps the version could be added to the name?

I have removed d4 so this is no longer an issue. 

> Did you copy-paste WAPS? If so, why? Can't it be a submodule? What's wrong with having it as a submodule?
> weighted-to-unweighted should be a submodule, not copy-pasted

I have made some changes to the code of WAPS and weighted-to-unweighted that are specific to our use case. 

>After you have fixed the unstripped binarye, squashing your commits is a must.

You are right! The binaries were not stripped, and I have updated the binaries with their stripped version.  I have also merged all the commits into a new branch "add_weights_clean"

Yash

**Comment by msoos** [comment]
Hi Yash,

Thanks for the explanation. However, a high-level point-by-point summary of what the difference is would be good to have. Also, if we are improving things, we may as well add test case(s) so you can verify that it's actually correct. I don't think this system has any test cases built in?

Note that merging the commits is not what we want. Please read up on `git rebase -i` and check how to "squash" commit. You can then squash all your commits into a single commit, and force-push that. Again, you actually need to read the manpage of `git` and read about squashing. Basically, you have to `git rebase -i HEAD^^^^^^^..^^^" and that will bring up an editor, where you have to replace all but one of your commits with a "squash" then save and exit. Merging/etc. will not do the trick. You need to squash and then force-push.

Incorporating the fixes here from Scalbarbarik sounds like a ton of work. The computational hardness part of ScalBarbarik was actually about 10 minutes of work once the code was cleaned. It took TONS of work to clean that codebase, which was the hard part. It would have been significantly easier to strip away the computational hardness thing from ScalBarbarik (about 10 minutes of work, at most), but re-incoporating the cleanup from there to here... I wouldn't wish that on my enemies. Next time, for this kind of work, I suggest asking around what previous work was already carried out. Check Scalbarbarik -- you would have only had to delete like 50 lines of code or something. Please do a `diff` between that codebase and barbarik, so you can see the large number of fixes and improvements that went into it. It really was non-trivial, and I would like you to appreciate the amount of work we are talking about, and the kind of work you'd be signing up for if you wanted to really port the changes from there to here.

It's a bit sad because I spent a lot of time giving feedback to Priyanka, and helping to fix up that codebase (e.g. stripping binaries -- she could have told you about this as well). Unfortunately, all that work will now be lost, because it'd be unrealistic for you to re-do that work.

Please don't forget to give a high level, say 10-point overview of what the changes are in this Barbarik relative to the previous Barbarik. It's a lot of change that you put in here, it'd be nice to be able to understand what I am supposed to look for. Thanks again for the improvement,

Mate

**Comment by yashpote** [comment]
Hi Mate,

Thanks for bearing with me on this.

Here are some of the changes, I will add more as i recall them. 

1. Barbarik and Weighted Barbarik can test a broader class of samplers than just CNF samplers. However, the current code is not modular enough to allow for extension to other samplers, so I have tried to separate the CNF part and the test part.  

2. In Barbarik, samples are represented around as strings. I have changed that so that samples are lists of literals. I think this is a better representation as this cuts down on the frequent type conversion.  

3. I have added WAPS as a weighted sampler. WAPS needed a few edits as it originally did not return the weighted count, and we need the weighted count in this algorithm.

4.  I have added code from the [unweighted-to-weighted](https://github.com/meelgroup/weighted-to-unweighted) to deal with the weighted CNF formulas. I had to modify the code slightly to make it return the independent variables after transformation. 

5. I have removed the "--minsamples" [flag](https://github.com/meelgroup/barbarik/blob/4f9a4bda27ce96dcb2760e0805ada4cfc9da2ed1/barbarik.py#L767) as it is not justified and will produces unintended behavior.

6. Barbarik had an [error](https://github.com/meelgroup/barbarik/blob/4f9a4bda27ce96dcb2760e0805ada4cfc9da2ed1/barbarik.py#L538) where  if the sampler got identical samples, it would repeat the experiment. That is not how the algorithm goes.

7. The "[ok](https://github.com/meelgroup/barbarik/blob/4f9a4bda27ce96dcb2760e0805ada4cfc9da2ed1/barbarik.py#L832)" variable is not useful so I have done away with that everywhere. 

8. The "experiment" framework in Barbarik is hard to work with as it is not in the paper, and is also hard to integrate with Weighted Barbarik. This is because, weighted barbarik has an exact sampler that has to compiled for every input, and we don't want to recompile it for every experiment.  If we try to accommodate for this, then experiment will become a leaky abstraction. 

Thanks,
Yash

**Comment by msoos** [comment]
Hi Yash,

Thanks! It's good to read through and understand, nice! Reading through, it seems like you have done a lot of refactoring. Nice! I just remembered, though -- Kuldeep & Priyanka caught a few **serious** bugs in Barbarik while cleaning up and finishing Scalbarbarik. Please ask Priyanka to make sure those bugs are not still present in your version. I'd rather not have to find and fix them again. *Please do confirm that you have talked with Priyanka and she has checked the code to make sure it doesn't have the bugs she and Kuldeep has fixed in Scalbarbarik.*

Regarding (4). This is not good engineering practice: `I have added code from the [unweighted-to-weighted](https://github.com/meelgroup/weighted-to-unweighted) to deal with the weighted CNF formulas. I had to modify the code slightly to make it return the independent variables after transformation.` The right way to do this is to port your changes to that codebase (i.e. copy-paste the file and create a pull request), and then make it a git module here. I'd suggest you do that -- makes sense, I think. Why have 2 versions when you can have one version :) Less maintenance, less surprises!

I understand that this may be an issue: `The "experiment" framework in Barbarik is hard to work with as it is not in the paper, and is also hard to integrate with Weighted Barbarik. This is because, weighted barbarik has an exact sampler that has to compiled for every input, and we don't want to recompile it for every experiment. If we try to accommodate for this, then experiment will become a leaky abstraction.` -- however, you didn't explain what you did to fix it. What was the fix? What did you do to make this situation better?

Thanks again for the description, I hope it also helped you to write it down, it's nice to see what one has accomplished :) Cheers,

Mate

**Comment by yashpote** [comment]
I have made some further improvements.

1) The code of "unweighted-to-weighted" is now a submodule and is used as a library in barbarik 
2) I have removed that  "experiment" loop to simplify the code ([loop](https://github.com/meelgroup/barbarik/blob/4f9a4bda27ce96dcb2760e0805ada4cfc9da2ed1/barbarik.py#L803))

**Pull request merged**
